import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="bg-gray-50 min-h-screen text-gray-900">
        <header className="w-full py-4 px-6 bg-white shadow flex items-center justify-between">
          <Link href="/recipes" className="text-2xl font-bold text-blue-600">
            Recipe Book
          </Link>
        </header>
        <main className="max-w-5xl mx-auto p-4 sm:p-8">{children}</main>
      </body>
    </html>
  );
}
